ini_open("gamedata.ini");
global.jump_key = ini_read_real("controls", "jump_key", vk_space);
global.cling_key = ini_read_real("controls", "cling_key", vk_lshift);
global.left_key = ini_read_real("controls", "left_key", ord("A"));
global.right_key = ini_read_real("controls", "right_key", ord("D"));
global.duck_key = ini_read_real("controls", "duck_key", ord("S"));
global.reset_key = ini_read_real("controls", "reset_key", ord("R"));
global.hardcore_enabled = ini_read_real("settings", "hardcore_mode", 0);
global.secret0 = ini_read_real("secrets", "0", 0);
global.secret1 = ini_read_real("secrets", "1", 0);
global.secret2 = ini_read_real("secrets", "2", 0);
global.secret3 = ini_read_real("secrets", "3", 0);
global.secret4 = ini_read_real("secrets", "4", 0);
global.secret5 = ini_read_real("secrets", "5", 0);
global.secret6 = ini_read_real("secrets", "6", 0);
global.secret7 = ini_read_real("secrets", "7", 0);
global.secret8 = ini_read_real("secrets", "8", 0);
global.secret9 = ini_read_real("secrets", "9", 0);
global.secret10 = ini_read_real("secrets", "10", 0);
global.secret11 = ini_read_real("secrets", "11", 0);
global.secret12 = ini_read_real("secrets", "12", 0);
global.secret13 = ini_read_real("secrets", "13", 0);
global.secret14 = ini_read_real("secrets", "14", 0);
ini_close();
